name: Test Cases Workflow
on:
  schedule: # Runs every day
    - cron: '0 0 * * *' 
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-artefact:
    name: Update this repo's README with latest test artefacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
        comment_tag_name: "test_artefact"
          feed_list: "https://dev.to/feed/gautamkrishnar"